### ISSUE TITLE
Shouldnt this repo be deleted?

### ISSUE THREAD

**Issue by fullpwn** [Alvarito050506/thetracker#3]
i mean is it gonna be revived? its been ages and idk

**Comment by Alvarito050506** [comment]
Hello! Sorry for the late response...

No, this repo shouldn't be deleted, at least from my point of view, since I would like to keep it for later reference. _However_, it could be archived. Since archiving means that you couldn't reply to this comment, I will archive it after receiving feedback (or after one month without response).

**Comment by fullpwn** [comment]
Yo! How have you been? It's been 10 months and you still haven't archived this comment lol!

**Comment by fullpwn** [comment]
I've moved on to iOS development but the only problem is I don't have a Mac🤣! I have made a Cydia repo! What do you do these days?

**Comment by Alvarito050506** [comment]
Hi!

> It's been 10 months and you still haven't archived this comment lol!

Yep, I completely forgot about this repo, haha... 10 months, wow.

> I've moved on to iOS development but the only problem is I don't have a Mac:rofl:!

Ah, that must be pain, but I guess it could be interesting :P

> I have made a Cydia repo!

Hmm, I'm curious, is it some kind of Debian repo?

> What do you do these days?

Well, not much really, but my main focus lately is @MCPI-Revival, and playing around with some Linux (Unix in general?)-related concepts I couldn't yet put in practice...

By the way, since I'm going to [finally] archive this repo, my e-mail address is `donfrutosgomez [at] [Google's email service] [dot] com`, if you want to continue talking :-)
